### ISSUE TITLE
Add `buffer_size` to buffered log handlers

### ISSUE THREAD

**Issue by homersimpsons** [thecodingmachine/symfony-boilerplate#1]
# Issue

Long running process might go out of memory (OOM) if buffered log handlers are filled

```php
while (true) {
    $this->bufferedLogHandler->info('test');
}
```

`fingers_crossed` is buffer based so it can run into this issue.

# Fix

A `buffer_size` should be append to the config. This settings will tell the handler to keep only the nth most recent messages so this will avoid OOM.

The configuration doc can be found [there](https://github.com/symfony/monolog-bundle/blob/master/DependencyInjection/Configuration.php#L19-L337) ([permalink](https://github.com/symfony/monolog-bundle/blob/ea721514c63fb0f65570ea785a9f441999f33ea7/DependencyInjection/Configuration.php#L19-L337))

A value of `100` should be far enough.

**Comment by gulien** [comment]
In the production configuration, there is already a buffer size: https://github.com/thecodingmachine/symfony-nuxtjs/blob/master/src/api/config/packages/prod/monolog.yaml#L8
