### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by gulien** [thecodingmachine/symfony-boilerplate#26]
^ from thecodingmachine Docker PHP images version 4.

**Comment by gulien** [comment]
`ecodev/graphql-upload` should be >= 6, but it requires `webonyx/graphql-php` 14. Alas, `thecodingmachine/graphqlite` is not yet migrated on  `webonyx/graphql-php` 14.

**Comment by gulien** [comment]
Also, PHP Code Sniffer: https://github.com/squizlabs/PHP_CodeSniffer/issues/3182

**Comment by mistraloz** [comment]
Fixed by !44
