### ISSUE TITLE
Would be pratical to know wich file come from the boilerplate

### ISSUE THREAD

**Issue by mhlsf** [thecodingmachine/symfony-boilerplate#5]
I would find practical for migrating project to the boilerplate to know which files come from the boilerplate. That way it is easier to know if the example files come from our project are from the boilerplate for example.

Something like : 

_This file come from the Symfony-Boilerplate, you may update it or delete it depending on your project needs_

**Comment by gulien** [comment]
No more revelant as the boilerplate is now "ready-to-user" (i.e., no more "unwanted" features).
